### PR TITLE
Some fixes to the generator tables

### PR DESCRIPTION
**Pull request by bje-**
These fixes correct some problems when using AREMI. I have reported these problems to AEMO, so hopefully they will be fixed upstream soon. I hope they can be fixed here for now.

### CODE REVIEW

**Comment by bje-** [comment]
Is there any interest in these fixes or should I follow up with AEMO to get the master lists corrected?

**Comment by meh9** [comment]
Definitely follow up with AEMO.

We are interested and I do want to apply these, but there just isn't any time right now. :(

**Comment by bje-** [comment]
Commits `ee533c8`, `679eaf5` and `0eae33e` are now implemented in the AEMO master spreadsheet. Can they be merged?

**Comment by bje-** [comment]
Ping?

**Pull request closed without merging**
